"""Generate example PDB files for consensus comparison demo.

Creates 3 synthetic structure predictions of the same hypothetical 20-residue
peptide as if predicted by AF3, Chai-1, and Boltz-2. The predictions have
realistic differences:
- Most residues agree (RMSD < 2 Å)
- One loop region (residues 8-12) shows divergence
- Confidence (B-factor / plDDT) is realistic per-residue

Run: python generate_example_data.py
Output: af3.pdb, chai1.pdb, boltz2.pdb
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

# Reproducibility
np.random.seed(42)

# Parameters
N_RESIDUES = 20
CA_CA_DIST = 3.8  # Å (standard backbone Cα-Cα distance)
OUTPUT_DIR = Path(__file__).parent


def generate_backbone(noise_std: float = 0.3) -> np.ndarray:
    """Generate a quasi-extended backbone with small random perturbations.

    Args:
        noise_std: Standard deviation of position noise (Å).

    Returns:
        Cα coordinates shape (N_RESIDUES, 3).
    """
    coords = np.zeros((N_RESIDUES, 3))
    for i in range(N_RESIDUES):
        coords[i] = [i * CA_CA_DIST, 0.0, 0.0]
    # Add small noise
    coords += np.random.normal(0, noise_std, coords.shape)
    return coords


def add_divergent_region(
    coords: np.ndarray,
    region_start: int,
    region_end: int,
    displacement_magnitude: float,
) -> np.ndarray:
    """Add a divergent region to a backbone (simulates loop disagreement).

    Args:
        coords: Original Cα coordinates.
        region_start: 0-indexed start of divergent region.
        region_end: 0-indexed end (inclusive).
        displacement_magnitude: Maximum displacement (Å).

    Returns:
        Modified coordinates with divergence.
    """
    coords = coords.copy()
    region_size = region_end - region_start + 1
    for i, idx in enumerate(range(region_start, region_end + 1)):
        # Gaussian shape — max displacement at center
        relative_pos = (i - region_size / 2) / (region_size / 2)
        scale = np.exp(-2 * relative_pos**2)  # Bell curve
        # Displace in y direction
        coords[idx] += [0, displacement_magnitude * scale, 0]
    return coords


def write_pdb(
    coords: np.ndarray,
    confidence: np.ndarray,
    output_path: Path,
    model_name: str,
) -> None:
    """Write Cα coordinates as a PDB file with confidence as B-factor.

    Args:
        coords: Cα coordinates shape (N_residues, 3).
        confidence: Per-residue confidence (used as B-factor).
        output_path: Output PDB file path.
        model_name: For PDB title field.
    """
    with output_path.open("w") as f:
        f.write(f"TITLE     {model_name.upper()} PREDICTION (DEMO DATA)\n")
        f.write("REMARK     Generated by DYNAFOLD Hub for demo purposes\n")
        f.write("REMARK     Hypothetical 20-residue peptide\n")

        for i, (xyz, b_factor) in enumerate(zip(coords, confidence)):
            atom_num = i + 1
            res_num = i + 1
            f.write(
                f"ATOM  {atom_num:5d}  CA  ALA A{res_num:4d}    "
                f"{xyz[0]:8.3f}{xyz[1]:8.3f}{xyz[2]:8.3f}"
                f"  1.00{b_factor:6.2f}           C\n"
            )

        f.write("END\n")
    print(f"✓ Written {output_path.name} ({len(coords)} residues)")


def main() -> None:
    """Generate three demo predictions with realistic differences."""
    print("Generating consensus demo data...")
    print(f"Output directory: {OUTPUT_DIR}\n")

    # Generate three "predictions" with controlled differences
    np.random.seed(42)
    af3_coords = generate_backbone(noise_std=0.3)
    af3_confidence = np.full(N_RESIDUES, 92.0)  # High global confidence
    af3_confidence[7:13] = 65.0  # Lower in loop region (AF3 also unsure)

    np.random.seed(123)
    chai1_coords = generate_backbone(noise_std=0.4)
    # Chai-1 places the loop slightly differently
    chai1_coords = add_divergent_region(
        chai1_coords, region_start=8, region_end=12, displacement_magnitude=4.0
    )
    chai1_confidence = np.full(N_RESIDUES, 89.0)
    chai1_confidence[7:13] = 62.0

    np.random.seed(456)
    boltz2_coords = generate_backbone(noise_std=0.4)
    # Boltz-2 places loop very differently (critical divergence)
    boltz2_coords = add_divergent_region(
        boltz2_coords, region_start=8, region_end=12, displacement_magnitude=7.5
    )
    boltz2_confidence = np.full(N_RESIDUES, 87.0)
    boltz2_confidence[7:13] = 55.0  # Boltz-2 less confident here

    # Write files
    write_pdb(af3_coords, af3_confidence, OUTPUT_DIR / "af3.pdb", "AlphaFold 3")
    write_pdb(chai1_coords, chai1_confidence, OUTPUT_DIR / "chai1.pdb", "Chai-1")
    write_pdb(boltz2_coords, boltz2_confidence, OUTPUT_DIR / "boltz2.pdb", "Boltz-2")

    print("\n✓ Demo data ready!")
    print("\nTry running:")
    print(
        "  dynafold compare af3.pdb chai1.pdb boltz2.pdb "
        "--names 'alphafold-3,chai-1,boltz-2'"
    )


if __name__ == "__main__":
    main()
